name:                bitstring
version:             0.1.0.0
github:              "kozlov721/bitstring"
license:             BSD3
author:              "Martin Kozlovský"
maintainer:          "kozlovsky.m7@gmail.com"
copyright:           "2022 Martin Kozlovský"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kozlov721/bitstring#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.11.1.0


library:
  source-dirs: src
  ghc-options:
    - -O2

tests:
  bitstring-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bitstring
    - HUnit
    - extra
    - QuickCheck
  bitstring-bigendian-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    cpp-options:
    - -DBIGENDIAN
    dependencies:
    - bitstring
    - HUnit
    - extra
    - QuickCheck
